SELECT DISTINCT C.CAR_ID, C.CAR_TYPE, ROUND(DAILY_FEE * 30 - (DAILY_FEE * 30 * (DISCOUNT_RATE/100))) AS FEE
FROM CAR_RENTAL_COMPANY_CAR C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H
ON C.CAR_ID = H.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND C.CAR_ID NOT IN (
                        SELECT CAR_ID
                        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                        WHERE TO_CHAR(START_DATE,'yyyy-mm-dd') BETWEEN '2022-11-01' AND '2022-11-30'
                        OR TO_CHAR(END_DATE,'yyyy-mm-dd') BETWEEN '2022-11-01' AND '2022-11-30'
                        OR (TO_CHAR(START_DATE,'yyyy-mm-dd') <= '2022-11-01' AND TO_CHAR(END_DATE,'yyyy-mm-dd') >= '2022-11-30'))
AND DURATION_TYPE = '30일 이상'
AND ROUND(DAILY_FEE * 30 - (DAILY_FEE * 30 * (DISCOUNT_RATE/100))) BETWEEN 500000 AND 2000000
ORDER BY FEE DESC, C.CAR_TYPE, C.CAR_ID DESC;

