-- -- 코드를 입력하세요
-- SELECT 
--     AO.ANIMAL_ID,
--     AO.NAME
-- FROM
--     ANIMAL_INS AI
-- RIGHT JOIN 
--     ANIMAL_OUTS AO

-- ON  
--     AO.ANIMAL_ID = AI.ANIMAL_ID
    
-- -- WHERE 
-- --     AI.ANIMAL_ID IS NULL
-- ORDER BY 
--     ANIMAL_ID

SELECT b.ANIMAL_ID, b.NAME
FROM ANIMAL_INS a RIGHT JOIN ANIMAL_OUTS b ON a.ANIMAL_ID = b.ANIMAL_ID
WHERE a.ANIMAL_ID IS NULL
ORDER BY ANIMAL_ID;