SELECT
    P.PRODUCT_ID,
    P.PRODUCT_NAME,
    SUM(P.PRICE * O.AMOUNT) as total_sales
FROM
    FOOD_PRODUCT P
JOIN
    FOOD_ORDER O ON P.PRODUCT_ID = O.PRODUCT_ID
where 
    TO_CHAR(O.PRODUCE_DATE,'YYYY-MM') = '2022-05'
GROUP BY 
    P.PRODUCT_ID, PRODUCT_NAME
ORDER BY
    total_sales desc,
    P.PRODUCT_ID asc;