-- SELECT b.CATEGORY, b.MAX_PRICE, a.PRODUCT_NAME
-- FROM FOOD_PRODUCT a JOIN (
--     SELECT CATEGORY, max(PRICE) AS MAX_PRICE
--     FROM FOOD_PRODUCT
--     GROUP BY CATEGORY
-- ) b ON a.CATEGORY = b.CATEGORY AND a.PRICE = b.MAX_PRICE
-- WHERE a.CATEGORY IN ('과자', '국', '김치', '식용유')
-- ORDER BY 2 DESC

SELECT A.CATEGORY, B.MAX_PRICE, A.PRODUCT_NAME
FROM FOOD_PRODUCT A
JOIN (
    SELECT CATEGORY, max(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
) B ON A.CATEGORY=B.CATEGORY and A.PRICE = B.MAX_PRICE
WHERE A.CATEGORY IN ('과자', '국', '김치', '식용유')
ORDER BY 2 DESC;
