-- SELECT 
-- SUBSTR(PRICE,1,1)*10000 AS PRICE_GROUP,
-- COUNT(*) AS RPODUCTS
-- FROM PRODUCT
-- GROUP BY SUBSTR(PRICE,1,1)*10000
-- ORDER BY SUBSTR(PRICE,1,1)*10000

SELECT TRUNC(PRICE,-4)  AS PRICE_GROUP, count(*)
FROM PRODUCT
GROUP BY TRUNC(PRICE,-4)
ORDER BY TRUNC(PRICE,-4)